### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by bitdynamicsapps** [RadiusNetworks/altbeacon-reference#2]
I want to use [Sourcegraph](https://sourcegraph.com) for altbeacon-reference code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/RadiusNetworks/altbeacon-reference. (It should only take 30 seconds.)

Thank you!

**Comment by davidgyoung** [comment]
done
